import test from "node:test";
import assert from "node:assert/strict";
import Fastify from "fastify";
import { prisma } from "../lib/prisma.js";
import { authRoutes } from "./auth.js";
import { createRegistrationVerification } from "../lib/registration-verification.js";
import { verificationTestDatabase } from "../lib/registration-verification.test-support.js";
import { verifyPassword } from "../lib/auth.js";

test("real verification service gates registration, sets flags, preserves password login and rolls back failures", async () => {
  const db = verificationTestDatabase();
  let deliveredCode = "";
  let time = new Date();
  const service = createRegistrationVerification(db, { now: () => time, hmacKey: () => "isolated-test-key-not-a-real-secret-123", assertDeliveryConfigured: () => {}, send: async (_email, code) => { deliveredCode = code; return "test-only-message"; } });
  const original = { transaction: prisma.$transaction, user: prisma.user, session: prisma.session };
  const mutable = prisma as any;
  mutable.$transaction = db.$transaction;
  mutable.user = db.user;
  mutable.session = db.session;
  process.env.JWT_ACCESS_SECRET = "isolated-test-access";
  process.env.JWT_REFRESH_SECRET = "isolated-test-refresh";
  const app = Fastify();
  await authRoutes(app, service);
  const post = (path: string, payload: any) => app.inject({ method: "POST", url: `/api/v1/auth/${path}`, payload });
  const registration = { fullName: "Customer One", email: "customer@example.com", password: "TestPassword123", phone: "015123456789", role: "OWNER", emailVerified: true };
  try {
    assert.equal((await post("register", registration)).statusCode, 400);
    assert.equal((await post("verification/request", { channel: "SMS", purpose: "CUSTOMER_REGISTRATION", email: registration.email })).statusCode, 400);
    const requested = await post("verification/request", { channel: "EMAIL", purpose: "CUSTOMER_REGISTRATION", email: " CUSTOMER@example.com " });
    assert.equal(requested.statusCode, 202);
    const challengeId = requested.json().challengeId;
    assert.equal(requested.body.includes(deliveredCode), false);
    assert.equal((await post("verification/resend", { challengeId })).statusCode, 429);
    const wrong = await post("verification/confirm", { challengeId, code: "000000" });
    assert.equal(wrong.statusCode, 400);
    const confirmation = await post("verification/confirm", { challengeId, code: deliveredCode });
    assert.equal(confirmation.statusCode, 200);
    const verificationToken = confirmation.json().verificationToken;
    assert.equal((await post("register", { ...registration, email: "other@example.com", verificationToken })).statusCode, 400);
    assert.equal((await post("register", { ...registration, phone: "+4415123456789", verificationToken })).statusCode, 400);
    const originalSessionCreate = db.session.create;
    db.session.create = async () => { throw new Error("test session failure"); };
    assert.equal((await post("register", { ...registration, verificationToken })).statusCode, 503);
    assert.equal((await db.user.findMany({})).length, 0);
    db.session.create = originalSessionCreate;
    const registered = await post("register", { ...registration, verificationToken });
    assert.equal(registered.statusCode, 200);
    const payload = registered.json();
    assert.equal(payload.user.role, "CUSTOMER");
    assert.equal(payload.user.emailVerified, true);
    assert.equal(payload.user.phoneVerified, false);
    assert.equal(payload.user.phone, "+4915123456789");
    assert.ok(payload.accessToken);
    assert.equal("passwordHash" in payload.user, false);
    assert.equal(registered.body.includes(registration.password), false);
    const user = await db.user.findUnique({ where: { email: registration.email } });
    assert.equal(await verifyPassword(user.passwordHash, registration.password), true);
    assert.equal((await post("register", { ...registration, verificationToken })).statusCode, 400);
    assert.equal((await post("login", { email: registration.email, password: registration.password })).statusCode, 200);
    time = new Date(time.getTime() + 61_000);
    const second = await post("verification/request", { channel: "EMAIL", purpose: "CUSTOMER_REGISTRATION", email: registration.email });
    const secondProof = await post("verification/confirm", { challengeId: second.json().challengeId, code: deliveredCode });
    assert.equal((await post("register", { ...registration, verificationToken: secondProof.json().verificationToken })).statusCode, 409);
    assert.equal((await db.registrationVerificationChallenge.findUnique({ where: { id: second.json().challengeId } })).consumedAt, null);
  } finally {
    mutable.$transaction = original.transaction; mutable.user = original.user; mutable.session = original.session;
    await app.close();
  }
});
